# Profile default
server:
  port: 8080
spring:
  application:
    name: app-pedido
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driverClassName: ${DATASOURCE_DRIVER}
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: "update"
      dialect: "org.hibernate.dialect.MySQL8Dialect"
pagamento:
  service:
    url: ${URL_SERV_PAGAMENTO}
producao:
  service:
    url: ${URL_SERV_PRODUCAO}

# Profile para a AWS
---
spring:
  config:
    activate:
      on-profile: dev

# Profile para rodar os testes
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}
    driverClassName: org.h2.Driver
  sql:
    init:
      schema-locations: classpath:schema-test.sql
      data-locations: classpath:data-test.sql
