# Profile default
server:
  port: 8080
spring:
  application:
    name: app-lanchonete
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: "update"
      dialect: "org.hibernate.dialect.MySQL8Dialect"
logging:
  level:
    root: INFO
    com.example: DEBUG
  logback:
    appender:
      console:
        class: ch.qos.logback.core.ConsoleAppender
        encoder:
          pattern: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    logger:
      root:
        level: INFO
        appender: console
      com.example:
        level: DEBUG
        appender: console

# Profile para a AWS
---
spring:
  config:
    activate:
      on-profile: dev

# Profile local para rodar com o H2
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    # defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
